# Generated by Django 2.2 on 2023-02-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='text',
        ),
        migrations.AddField(
            model_name='articles',
            name='adress',
            field=models.CharField(default='', max_length=200, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_2',
            field=models.CharField(default='', max_length=200, verbose_name='Имя, отчество'),
        ),
        migrations.AddField(
            model_name='articles',
            name='ph_num',
            field=models.CharField(default='', max_length=200, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='articles',
            name='position',
            field=models.CharField(default='', max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
    ]
