# Generated by Django 2.2 on 2023-02-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230215_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Работника', 'verbose_name_plural': 'Работники'},
        ),
    ]
